### ISSUE TITLE
Ocassionally, our hi-low rolls will be incorrect during a tie

### ISSUE THREAD

**Issue by telusive** [manistal/calmdownandgamble#5]
Most times it works fine, but occasionally, the addon will use the second roll from the tie-breaker to decide the amount, instead of the first roll

**Comment by phoones** [comment]
This is currently a known bug, High tiebreakers will evaluate the payout
based on the winners high roll, and low tiebreakers will payout based on
the losers low roll, instead of the two original rolls.

It's a real tough one to track down and fix though, we've been trying for a
while...
